USE [master]
GO

/****** Object:  Database [DataChat]    Script Date: 12/13/2015 9:55:32 AM ******/
CREATE DATABASE [DataChat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataChat', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.THANHHIEU\MSSQL\DATA\DataChat.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DataChat_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.THANHHIEU\MSSQL\DATA\DataChat_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DataChat] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataChat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataChat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataChat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataChat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataChat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataChat] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataChat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataChat] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DataChat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataChat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataChat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataChat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataChat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataChat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataChat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataChat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataChat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataChat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataChat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataChat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataChat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataChat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataChat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataChat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataChat] SET RECOVERY FULL 
GO

ALTER DATABASE [DataChat] SET  MULTI_USER 
GO

ALTER DATABASE [DataChat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataChat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataChat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataChat] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DataChat] SET  READ_WRITE 
GO

